apiVersion: v1
kind: Service
metadata:
  name: taxiservice
  labels:
    app: taxiservice
spec:
  ports:
    - port: 80
  selector:
    app: taxiservice
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: taxiservice
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: taxiservice
  labels:
    app: taxiservice
spec:
  selector:
    matchLabels:
      app: taxiservice
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: taxiservice
        tier: frontend
    spec:
      containers:
      - image: sandeepgiri9/taxicounterk8sm:service
        name: taxiservice
        env:
        - name: taxiservice_DB_HOST
          value: taxiservice-mysql
        - name: taxiservice_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: taxiservice
        volumeMounts:
        - name: taxiservice-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: taxiservice-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
